#!/usr/bin/env php
<?php
echo "Simple Modman Generator v0.1.4" . PHP_EOL;
$ignoreFiles = array(
    'modman',
    'composer\.json',
    'composer\.lock',
    '\.gitignore',
    'README\.md',
    'LICENSE',
);
$ignoreFiles = implode('|', $ignoreFiles);
$files = `git ls-files | grep -vE "($ignoreFiles)"`;

//match directories
preg_match_all(
    '~^app/code/([A-z_]+/){3}|app/etc/modules/[^\n]*|app/design/([^/\n]+/?){6}|(shell|js|skin)/[^\n]+|lib/[A-z]+/~s',
    $files, $matches
);
$list = array_unique($matches[0]);
if (!$list) {
    echo "error: No files found under GIT to place into 'modman' file." . PHP_EOL;
    return;
}

//find long string
$maxLength = max(array_map('strlen', $list));

//make output
foreach ($list as $item) {
    if (is_file($item)) {
        $space = str_repeat(' ', $maxLength - strlen($item) + 3);
    } else {
        $item = rtrim($item, '/') . '/';
        $space = str_repeat(' ', $maxLength - strlen($item) + 2);
    }
    $output[] = "$item $space $item";
}
$output = implode("\n", $output);

//get GIT root path
$gitRoot = trim(`git rev-parse --show-toplevel`);
//make absolute path to modman file
$file = $gitRoot . DIRECTORY_SEPARATOR . 'modman';

if (false === file_put_contents($file, $output)) {
    echo "error: 'modman' cannot be generated." . PHP_EOL;
} else {
    echo "'modman' file generated." . PHP_EOL;
}

